blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs'),
    path('create/blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update/blog/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('detail/blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('delete/blog/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('client.urls', namespace='client')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    path('messages/', cache_page(60)(MessageListView.as_view()), name='messages'),
    path('create/message/', MessageCreateView.as_view(), name='create_message'),
    path('update/message/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('detail/message/<int:pk>', cache_page(60)(MessageDetailView.as_view()), name='message_detail'),
    path('delete/message/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('settings/', MailingSettingsListView.as_view(), name='settings'),
    path('create/settings/', MailingSettingsCreateView.as_view(), name='create_settings'),
    path('update/settings/<int:pk>', MailingSettingsUpdateView.as_view(), name='settings_update'),
    path('detail/settings/<int:pk>', MailingSettingsDetailView.as_view(), name='settings_detail'),
    path('delete/settings/<int:pk>', MailingSettingsDeleteView.as_view(), name='settings_delete'),
    path('logs/', cache_page(60)(MailingLogsListView.as_view()), name='logs'),
]

mailing/models.py
from django.db import models
from client.models import Client
from users.models import User


PERIODICITY_CHOICES = [
    ('Daily', 'Раз в день'),
    ('Weekly', 'Раз в неделю'),
    ('Monthly', 'Раз в месяц'),
]


STATUS_CHOICES = [
    ('Started', 'В процессе'),
    ('Completed', 'Завершена'),
]


class Message(models.Model):
    """
    Модель для сообщения рассылки
    """
    heading = models.CharField(max_length=100, verbose_name='Тема')
    body = models.TextField(verbose_name='Текст')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'Рассылка на тему: "{self.heading}".'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MailingSettings(models.Model):
    """
    Модель для настроек рассылки
    """
    name = models.CharField(max_length=100, verbose_name='Наименование рассылки')
    mailing_time = models.TimeField(verbose_name='Время рассылки')
    mailing_date = models.DateField(verbose_name='Дата рассылки')
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Started', verbose_name='Статус рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'{self.mailing_time} - {self.periodicity}'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'


class MailingLogs(models.Model):
    """
    Модель логов отправки рассылок
    """
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, verbose_name='Сообщение')
    datatime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=30, verbose_name='Статус попытки')
    server_answer = models.TextField(verbose_name='Ответ почтового сервера')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'{self.message} - {self.status}'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms
from mailing.models import Message, MailingSettings
from client.forms import StyleFormMixin


class MessageForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для сообщения рассылки
    """
    class Meta:
        model = Message
        fields = '__all__'


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для настроек рассылки
    """
    class Meta:
        model = MailingSettings
        exclude = ('user', 'status',)

mailing/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from mailing.forms import MessageForm, MailingSettingsForm
from mailing.models import Message, MailingSettings, MailingLogs
from django.contrib.auth.mixins import LoginRequiredMixin


class MessageListView(ListView):
    """
    Контроллер для всех созданных сообщений
    """
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания нового сообщения
    """
    model = Message
    form_class = MessageForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для обновления данных в сообщении
    """
    model = Message
    form_class = MessageForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления сообщения
    """
    model = Message
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра данных сообщения
    """
    model = MailingSettings
    login_url = 'users:login'


class MailingSettingsListView(LoginRequiredMixin, ListView):
    """
    Контроллер для вывода всех вариантов настроек рассылки
    """
    model = MailingSettings
    login_url = 'users:login'


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания новых настроек рассылки
    """
    model = MailingSettings
    form_class = MailingSettingsForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для обновления данных в настройках рассылки
    """
    model = MailingSettings
    form_class = MailingSettingsForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления настроек рассылки
    """
    model = MailingSettings
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class MailingSettingsDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра данных о настройках рассылки
    """
    model = MailingSettings
    login_url = 'users:login'


class MailingLogsListView(LoginRequiredMixin, ListView):
    """
    Контроллер для всех созданных сообщений
    """
    model = MailingLogs
    login_url = 'users:login'

mailing/templates/mailing/mailinglogs_list.html
{% extends 'home/base.html' %}

{% block content %}

<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Сообщение</th>
        <th scope="col">Дата и время последней попытки</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ почтового сервера</th>
    </tr>
    </thead>
    {% for object in object_list %}
    <tbody>
    <tr>
        <td>{{ object.message }}</td>
        <td>{{ object.datatime_attempt }}</td>
        <td>{{ object.status }}</td>
        <td>{{ object.server_answer }}</td>
    </tr>
    </tbody>
    {% endfor %}
</table>

{% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить настройки рассылки:
                            "{{ object.mailing_time }} - {{ object.periodicity }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:settings' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailingsettings_detail.html
{% extends 'home/base.html' %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <div class="col-12">
            <div class="card-header">
                <p class="card-text">Время рассылки: {{ object.mailing_time }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">Переодичность: {{ object.periodicity }}</p>
                <p class="card-text">Статус: {{ object.status }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:settings_detail' object.pk %}" type="button" class="btn btn-success">Редактировать</a>
                <a href="{% url 'mailing:settings' %}" type="button" class="btn btn-warning">Назад</a>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'home/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Обновить информацию в настройках рассылки
                {% else %}
                    Создать новые настройки для рассылки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Обновить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'home/base.html' %}

{% block content %}

{% if user.role == 'manager' or user.is_superuser %}
<div class="col-12 mb-5">
    <a href="{% url 'mailing:create_settings' %}" type="button"
       class="btn btn-primary">Создать новые настройки рассылки</a>
</div>
{% endif %}

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <p class="card-text">{{ object.name }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">Время отправки: {{ object.mailing_time }}</p>
                <p class="card-text">Периодичность: {{ object.periodicity}}</p>
                {% if user.role == 'manager' or user.is_superuser %}
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                    <label class="form-check-label" for="flexSwitchCheckChecked">{{ status }} Активная рассылка</label>
                </div>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:settings_detail' object.pk %}" type="button"
                   class="btn btn-success">Просмотр</a>
                {% if user.is_superuser %}
                <a href="{% url 'mailing:settings_update' object.pk %}" type="button"
                   class="btn btn-warning">Изменить</a>
                <a href="{% url 'mailing:settings_delete' object.pk %}" type="button"
                   class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить сообщение "{{ object.heading }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:messages' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'home/base.html' %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <div class="col-12">
            <div class="card-header">
                <p class="card-text">Тема: {{ object.heading }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">Текст письма: {{ object.body }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:message_detail' object.pk %}" type="button" class="btn btn-success">Редактировать</a>
                <a href="{% url 'mailing:messages' %}" type="button" class="btn btn-warning">Назад</a>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'home/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Обновить информацию в сообщении
                {% else %}
                    Создать новое сообщение для рассылки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Обновить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'home/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a href="{% url 'mailing:create_message' %}" type="button" class="btn btn-primary">Создать новую рассылку</a>
</div>

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <p class="card-text">{{ object.heading }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailing:message_detail' object.pk %}" type="button" class="btn btn-success">Просмотр</a>
                {% if user.role == 'manager' or user.is_superuser %}
                <a href="{% url 'mailing:message_update' object.pk %}" type="button" class="btn btn-warning">Изменить</a>
                <a href="{% url 'mailing:message_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}