blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs'),
    path('create/blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update/blog/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('detail/blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('delete/blog/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

client/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from client.apps import ClientConfig
from client.views import *

app_name = ClientConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='clients'),
    path('create/client/', cache_page(60)(ClientCreateView.as_view()), name='create_client'),
    path('update/client/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('detail/client/<int:pk>', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('delete/client/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('client.urls', namespace='client')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Модель клиента рассылки
    """
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(unique=True, verbose_name='Email')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    phone = models.CharField(max_length=25, **NULLABLE, verbose_name='Телефон')
    registration_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')
    user = models.ManyToManyField(User, verbose_name='Пользователь')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f"{self.first_name} {self.last_name} (email: {self.email})"

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('first_name', 'last_name', 'registration_date',)

client/forms.py
from django import forms
from client.models import Client


class StyleFormMixin:
    """
    Миксин для стиля форм
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для клиентов рассылки
    """
    class Meta:
        model = Client
        exclude = ('user', )

client/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from client.forms import ClientForm
from client.models import Client
from django.contrib.auth.mixins import LoginRequiredMixin


class ClientListView(LoginRequiredMixin, ListView):
    """
    Контроллер для вывода всех клиентов рассылки
    """
    model = Client
    login_url = 'users:login'


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания клиента рассылки
    """
    model = Client
    form_class = ClientForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')

    def get_context_data(self, **kwargs):
        """
        Метод получения контекста
        """
        context_data = super().get_context_data()
        user = self.request.user
        context_data['user'] = user
        return context_data

    def form_valid(self, form):
        """
        Метод получения данных из формы
        """
        if form.is_valid():
            user = self.request.user
            new_user = form.save()
            new_user.user.add(user)
            new_user.save()
            return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для обновления данных о клиенте рассылки
    """
    model = Client
    form_class = ClientForm
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления клиента рассылки
    """
    model = Client
    login_url = 'users:login'
    success_url = reverse_lazy('client:clients')


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра данных клиента
    """
    model = Client
    login_url = 'users:login'

client/templates/client/client_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить клиента "{{ object.first_name }} {{ object.last_name }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'client:clients' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

client/templates/client/client_detail.html
{% extends 'home/base.html' %}

{% block content %}


<div class="container">
    <div class="row text-start">
        <div class="col-12">
            <div class="card-header">
                <p class="card-text">Имя: {{ object.first_name }}</p>
                <p class="card-text">Фамилия: {{ object.last_name }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">Телефон: {{ object.phone }}</p>
                <p class="card-text">Почта: {{ object.email }}</p>
                <p class="card-text">Дата регистрации: {{ object.registration_date }}</p>
                <br>
                <p class="card-text">Комментарий: {{ object.comment }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'client:client_detail' object.pk %}" type="button" class="btn btn-success">Редактировать</a>
                <a href="{% url 'client:clients' %}" type="button" class="btn btn-warning">Назад</a>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

client/templates/client/client_form.html
{% extends 'home/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Обновить данные о клиенте рассылки
                {% else %}
                    Создать нового клиента для рассылки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Обновить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

client/templates/client/client_list.html
{% extends 'home/base.html' %}

{% block content %}

{% if user.is_superuser %}
<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'client:create_client' %}">Создать нового клиента</a>
</div>
{% endif %}

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <p class="card-text">{{ object.first_name }}</p>
                <p class="card-text">{{ object.last_name }}</p>
            </div>
            <div class="card-body">
                <p class="card-text">Почта: {{ object.email }}</p>
                <p class="card-text">Телефон: {{ object.phone }}</p>
                <p class="card-text">Дата регистрации: {{ object.registration_date }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'client:client_detail' object.pk %}" type="button" class="btn btn-success">Просмотр</a>
                {% if user.role == 'manager' or user.is_superuser %}
                <a href="{% url 'client:client_update' object.pk %}" type="button" class="btn btn-warning">Изменить</a>
                <a href="{% url 'client:client_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}