blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs'),
    path('create/blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update/blog/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('detail/blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('delete/blog/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('client.urls', namespace='client')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from client.models import NULLABLE


class Blog(models.Model):
    """
    Модель блога
    """
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    date_of_published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        """
        Возвращение строкового представления объекта
        """
        return f'Блог: {self.title}'

    class Meta:
        """
        Настройки для наименования объекта/объектов
        """
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('title', 'date_of_published',)

blog/forms.py
from django import forms
from blog.models import Blog
from client.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title', 'content', 'preview',)

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from blog.forms import BlogForm
from blog.models import Blog
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения всех записей блога
    """
    model = Blog
    login_url = 'users:login'


class BlogCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания новой статьи блога
    """
    model = Blog
    form_class = BlogForm
    login_url = 'users:login'
    success_url = reverse_lazy('blog:blogs')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для обновления данных в статье блога
    """
    model = Blog
    form_class = BlogForm
    login_url = 'users:login'
    success_url = reverse_lazy('blog:blogs')


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления статьи блога
    """
    model = Blog
    login_url = 'users:login'
    success_url = reverse_lazy('blog:blogs')


class BlogDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра статьи блога
    """
    model = Blog
    login_url = 'users:login'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Вы действительно хотите удалить данную статью?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'blog:blogs' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'home/base.html' %}

{% load my_tags %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-12">
            <img class="card-img-top" src="{{ object.preview|mediapath }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.content }}</p>
            </div>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'home/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                    Обновить данные в статье
                {% else %}
                    Создать новую статью
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Обновить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'home/base.html' %}

{% load my_tags %}

{% block content %}

{% if user.role == 'content_manager' or user.is_superuser %}
<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'blog:create_blog' %}">Создать новый блог</a>
</div>
{% endif %}

<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.preview|mediapath }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text"><b>{{ object.title }}</b></p>
                <p class="card-text">{{ object.content|truncatechars:150 }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:blog_detail' object.pk %}" type="button" class="btn btn-success">Просмотр</a>
                {% if user.role == 'content_manager' or user.is_superuser %}
                <a href="{% url 'blog:blog_update' object.pk %}" type="button" class="btn btn-warning">Изменить</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}