blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs'),
    path('create/blog/', BlogCreateView.as_view(), name='create_blog'),
    path('update/blog/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('detail/blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('delete/blog/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('client.urls', namespace='client')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views.fbv import generate_new_password, verify_email
from users.views.cbv import LoginView, LogoutView, RegisterView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verify/<str:token>/', verify_email, name='verify'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """
    Модель для пользователя платформы
    """
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)

    verification_key = models.CharField(max_length=255, verbose_name='ключ верификации', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from client.forms import StyleFormMixin
from users.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма для регистрации пользователя платформы
    """
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ProfileForm(StyleFormMixin, UserChangeForm):
    """
    Форма для работы с профилем пользователя платформы
    """
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views/cbv.py
import secrets
from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import CreateView, UpdateView
from users.forms import RegisterForm, ProfileForm
from users.models import User


class LoginView(BaseLoginView):
    """
    Контроллер входа в учетную запись
    """
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    """
    Контроллер выхода из учетной записи
    """
    pass


class RegisterView(CreateView):
    """
    Контроллер для регистрации пользователя на платформе
    """
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        new_user.verification_key = secrets.randbelow(1_000_000)
        new_user.save()

        token = urlsafe_base64_encode(force_bytes(new_user.verification_key))
        verification_url = reverse('users:verify', kwargs={'token': token})
        send_mail(
            subject='Заверешение регистрации на Mail Manager by 13|28',
            message=f'Для подтвердения регистрации, пройдите по ссылке ниже: \n {self.request.build_absolute_uri(verification_url)}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)

class UserUpdateView(UpdateView):
    """
    Контролер для работы с профилем пользователя
    """
    model = User
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/views/fbv.py
from random import randint
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.http import urlsafe_base64_decode
from users.models import User


@login_required
def generate_new_password(request):
    """
    Контроллер для генерации нового пароля для пользователя и отправка его на почту
    """
    new_password = ''.join([str(randint(0, 9)) for _ in range(10)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('client:clients'))


def verify_email(request, token):
    try:
        user_verification_key = urlsafe_base64_decode(token).decode()
        user = User.objects.get(verification_key=user_verification_key)
        if int(user_verification_key) == int(user.verification_key):
            user.is_active = True
            user.save()
            messages.success(request, 'Ваш аккаунт был успешно подтвержден. Теперь вы можете войти.')
            return redirect('home:home')
        else:
            messages.error(request, 'Ошибка верификации аккаунта.')
            return HttpResponse("Ошибка верификации аккаунта.")
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        messages.error(request, 'Ошибка верификации аккаунта.')
        return HttpResponse("Ошибка верификации аккаунта.")

users/templates/users/login.html
{% extends 'home/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Вход в систему
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Вход</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'home/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Регистрация
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Регистрация</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'home/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card-header">
            Мой профиль
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
        </div>
    </div>
</div>

{% endblock %}